version: "3.8"

services:
  redpaths-server:
    container_name: redpaths-server
    hostname: redpaths-server
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        INSTALL_TOOLS: "default"
    image: redpaths-server:latest
    ports:
      - "8081:8081"
      - "8082:8082"
 #   volumes:
 #     - ./src:/app/src
    environment:
      - GO_ENV=development
      # Postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=redpaths
      - POSTGRES_PASSWORD=redpaths
      - POSTGRES_DB=redpaths
      # Dgraph
      - DGRAPH_HOST=alpha
      - DGRAPH_PORT=9080
    restart: unless-stopped
    depends_on:
      - postgres
      - zero
      - ratel
      - alpha
    networks:
      - redpaths_network

  zero:
    image: dgraph/dgraph:latest
    volumes:
      - zero_datav3:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
    networks:
      - redpaths_network

  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - alpha_datav3:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:9080 --zero=zero:5080 --security whitelist=0.0.0.0/0
    networks:
      - redpaths_network

  ratel:
    image: dgraph/ratel:latest
    ports:
      - 8000:8000
    networks:
      - redpaths_network

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: "redpaths"
      POSTGRES_USER: "redpaths"
      POSTGRES_PASSWORD: "redpaths"
    volumes:
      - postgres_datav3:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - redpaths_network
    restart: on-failure
networks:
  redpaths_network:
    driver: bridge
    name: redpaths_network

volumes:
  zero_datav3:
  alpha_datav3:
  postgres_datav3: